# Generated by Django 4.0.6 on 2022-07-20 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('text', models.TextField(verbose_name='Описание задачи')),
                ('role', models.CharField(choices=[('NEW', 'New'), ('INPROGRESS', 'In progress'), ('COMPLETED', 'Completed')], max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('edit_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('image', models.ImageField(null=True, upload_to='todolist/%Y/%m/%d/', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('worker', models.ManyToManyField(blank=True, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-pub_date'],
            },
        ),
    ]
