# Generated by Django 4.0.6 on 2022-07-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='role',
            new_name='status',
        ),
    ]
