# Generated by Django 4.0.6 on 2022-07-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_role_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='todolist/%Y/%m/%d/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Картинки',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ManyToManyField(to='todolist.image'),
        ),
    ]
