# Generated by Django 4.0.6 on 2022-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_remove_task_image_task_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
    ]
