# Generated by Django 4.0.6 on 2022-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_task_image_taskimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
