# Generated by Django 4.0.6 on 2022-07-21 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0008_remove_task_image_remove_task_worker_taskimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ManyToManyField(blank=True, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
